spring:
  application:
    name: gostsNaumen
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_URL}:${POSTGRES_DB_PORT}/${POSTGRES_DB_NAME}
    username: ${POSTGRES_DB_USERNAME}
    password: ${POSTGRES_DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: ${MULTIPART_SIZE}
      max-request-size: ${MULTIPART_REQUEST_SIZE}
      location: ${MULTIPART_LOCATION}
      file-size-threshold: ${MULTIPART_SIZE_THRESHOLD}
      enabled: ${MULTIPART_ENABLED}

app:
  jws:
    secret: ${JWS_SECRET}
  jwe:
    secret: ${JWE_SECRET}
  expireMinutes: ${EXPIRE_MINUTES}